# TCP队列监控服务配置文件
kubernetes:
  # 是否使用集群内配置（在 Pod 内运行时设为 true），若为 false 则使用 kubeconfig 文件
  use_in_cluster: false

  # kubeconfig 文件路径（仅在 use_in_cluster 为 false 且在集群外使用时生效）
  kube_config_path: "/root/.kube/config"

  # 目标监控的命名空间（即哪些 Pod 属于要监控的业务）
#  target_namespace: 
#    - "ebpay"
  target_namespaces: 
    - "ebpay"
    - "koipay"

  # 忽略的容器名列表（如 Sidecar、Agent）
  ignore_containers:
    - filebeat
    - consul-client
    - istio-proxy


  # 最大并发数
  max_concurrent: 80
  max_pod_container: 40

  # 本地存储 Pod 列表快照的文件路径
  cache_file_path: "pod_snapshot.json"

server:
  # HTTP服务监听端口
  port: 9325

  # 日志级别: debug | info | warn | error
  log_level: "debug"

  # Gin运行模式: debug | release
  gin_mode: "release"
