apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-exporter
  namespace: ebpay-mid
  labels:
    app: tcp-exporter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tcp-exporter
  template:
    metadata:
      labels:
        app: tcp-exporter
    spec:
      serviceAccountName: tcp-exporter
      containers:
      - name: tcp-exporter
        image: harbor.ybfpay.net/library/tcp-exporter:latest
        imagePullPolicy: IfNotPresent
        args:
          - "--config=/app/config/config.yaml"
        env:
          - name: REPLICA_COUNT
            value: "3"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        ports:
          - name: http
            containerPort: 9325
            protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 2Gi
        volumeMounts:
          - name: config-volume
            mountPath: /app/config
            readOnly: true
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: tcp-exporter-config
            defaultMode: 420